# Generated by Django 5.2 on 2025-06-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layanan',
            options={'verbose_name': 'Layanan', 'verbose_name_plural': 'Layanan'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
